services:
  get-es-index-sizes:
    image: face0b1101/get-es-index-sizes:0.1
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      args:
        DOCKER_BUILDKIT: 1
    container_name: get-es-index-sizes
    volumes:
      - ./output:/output
    env_file:
      - .env
    restart: unless-stopped
